### ISSUE TITLE
custom name for collection ?

### ISSUE THREAD

**Issue by Sithira** [duyluonglc/lucid-mongo#111]
Can we have a custom name for the collection in the model?

**Comment by duyluonglc** [comment]
Try this
```
class User extends Model {
  static get collection () {
    return 'my_users'
  }
}
```

**Comment by Sithira** [comment]
I tried that before posting the issue. Didn't worked. I used Adonis 4.1

**Comment by rhnkyr** [comment]
I have the same issue.

**Comment by duyluonglc** [comment]
![image](https://user-images.githubusercontent.com/14918470/42047568-d4eaf434-7b2a-11e8-8833-c203c52b629d.png)
@Sithira @rhnkyr I dont see any issue with custom collection
check the example here
https://github.com/duyluonglc/adonis-mongdb-session-login-test

**Comment by rhnkyr** [comment]
@duyluonglc You may close this issue.
