### ISSUE TITLE
ENGINE_EXCEPTION invalid mongo uri when using mongo+srv://

### ISSUE THREAD

**Issue by wesleysaraujo** [duyluonglc/lucid-mongo#121]
Hello, in my adonisjs application I'm using Lucid Mongo, I like db mongo I'm using Atlas, in my environment setting I'm setting DB_HOST to url which is mongo + srv: // ... however this gives an error when I try do some connection operation in the bank:

Error:
"Invalid mongodb uri" mongodb + srv: ... "Must begin with" mongodb: // ""

How do I get around this error?

**Comment by duyluonglc** [comment]
sorry I did not have time to invest to your issue. should be included in next version

**Comment by nir-jas** [comment]
Is this fixed? Facing same problem

**Comment by duyluonglc** [comment]
fixed in v3.1.5
