### ISSUE TITLE
 andWhere() is not a function in lucid-mongo 3.1.0

### ISSUE THREAD

**Issue by marwenB** [duyluonglc/lucid-mongo#127]
Hello,

I've noticed that the where().andWhere() does no longer exist in the last version of lucid-mongo 
Is it just momentary or we need to deal it with another way ? 

Data.query(...).where(...).andWhere is not a function

**Comment by isocroft** [comment]
@marwenB have you been able to solve this issue you were having ?

**Comment by duyluonglc** [comment]
you can do like this:
```js
Data.query(...).where(...).where('...').where('...')
```
why you need `andWhere`?
