### ISSUE TITLE
Connection won't close when ace command finished

### ISSUE THREAD

**Issue by rusjoan** [duyluonglc/lucid-mongo#130]
Easy to reproduce:
1. create new ace command
2. call something like `const user = await User.findBy('blah-blah', 1)` in `handle()` method of "ace command"
3. call `this.info('test')`
4. Run ace command — you will see that 'test' printed in console but command isn't stopped

This is caused by non-closing mongo client, so what to do?

Thanks!

**Comment by NicoG11** [comment]
Try this 

```javascript
// put this the top of your ace command file
const Database = use('Database')


async handle (args, options) {
    // your code

    this.info('----------- ende / finish -----------')
    // put close at the end in your handle method
    await Database.close()
}
```
