### ISSUE TITLE
[question] how stable is this project?

### ISSUE THREAD

**Issue by pimlie** [duyluonglc/lucid-mongo#14]
The readme mentions this project is still a work in progress, but version 1 has been released. How stable is this? Is it ready for production? If not, is there some sort of a roadmap?

**Comment by duyluonglc** [comment]
@pimlie thank for interesting of my package. 
1. This package is forked and has features of adonis-lucid and the adonis-lucid is still work on progress https://github.com/adonisjs/adonis-lucid
2. Many test file need to be rewrite but I have no time to do
3. The Adonis framework going to release v4.0. I think this package need to update to 2.x to support
Current I use this for my prod. I think it can use for prod. :)
