### ISSUE TITLE
Does this support mongodb methods?

### ISSUE THREAD

**Issue by twigs67** [duyluonglc/lucid-mongo#145]
When I try:

```
let dbo = Database.connection('mongodb');

var myobj = { name: "Company Inc", address: "Highway 37" };

dbo.collection("customers").insertOne(myobj, function(err, res) {
  if (err) throw err;
  console.log("1 document inserted");
  db.close();
});
```
I get:
```
Error: Database.insertOne is not a function
```
But looking at the object there doesn't seem to be a way to access the mongo methods. Is there? Or are we forced to use Lucid methods only?

Thanks

**Comment by duyluonglc** [comment]
@twigs67 see here
https://github.com/duyluonglc/lucid-mongo#get-mongodb-client-object
