### ISSUE TITLE
Raw aggregation

### ISSUE THREAD

**Issue by protzi** [duyluonglc/lucid-mongo#148]
Hi guys, how to use raw aggregation from the model ?
https://github.com/duyluonglc/lucid-mongo/blob/40af7d524c90e87fd29dec7b8c1e56515b95bd8c/src/LucidMongo/QueryBuilder/index.js#L924

Can I use somehow this method?

```
User.aggregate([ /* here my raw query for aggregation */ ])
```

UPD:
Seems working 
``` User.where({}).aggregate(pipeline) ```
Please confirm am I right ?

**Comment by duyluonglc** [comment]
@protzi 
Try this and let me know result
```js
const result = await User.query().aggregate(pipeline)
```
