### ISSUE TITLE
LucidMongo always expects fixed user() relation on token authentication

### ISSUE THREAD

**Issue by synegic** [duyluonglc/lucid-mongo#156]
Hello! It seems that LucidMongo always uses the user() method on the token model. This prevents complexer use cases such as using two different authenticator models within the same project. It also prevents using model names other than 'user' on the token relationship.

Fixed it locally by changing the db lookup on line 179 in LucidMongoSerializer.js;

```javascript
      const user = await token.user().first()
```
to
```javascript
      const user = await token[this._Model.name.toLowerCase()]().first()
```

But there might be more elegant ways..

**Comment by duyluonglc** [comment]
You are right. If you have two different authenticators, you can:
1. try with morphMany - morphTo
2. write your owner App/Serializers/MySerializer.js then config auth to use it

**Comment by synegic** [comment]
Thanks! Fixed it for now by extending LucidMongoProvider and LucidMongoSerializer with my own override class.
