### ISSUE TITLE
belongsToMany Not Working 

### ISSUE THREAD

**Issue by websenornarendra** [duyluonglc/lucid-mongo#159]
My problem is as follows:

I have two tables 

Users 
Cars

When Attach Cares Record to user table then it's work But when fetch user Record with cars it's give null Value 

  cars () {
    return this.belongsToMany('App/Models/Cars')
  } 

Result

{
  name:"Test User",
  cars:[],
}

**Comment by duyluonglc** [comment]
Check this test case:
https://github.com/duyluonglc/lucid-mongo/blob/204089214b798b05250485af83d3e9937364ed0b/test/unit/lucid-belongs-to-many.spec.js#L354
I dont know what's exactly problem with your case
You can run code with mquery debug to see what's problem
`DEBUG=mquery adonis serve --dev`
