### ISSUE TITLE
BelongsToMany method detach đang xử lý sai.

### ISSUE THREAD

**Issue by haclongkim** [duyluonglc/lucid-mongo#160]
Mình đang override lại class BelongsToMany và sửa method detach thêm dòng 
```
    query.where(this.foreignKey, this.$primaryKeyValue)
```

---> cụ thể sẽ thành 
```
detach (references) {
    const query = this.pivotQuery(false)

    query.where(this.foreignKey, this.$primaryKeyValue)
    if (references) {
      const rows = !Array.isArray(references) ? [references] : references
      query.whereIn(this.relatedForeignKey, rows)
      _.remove(this._existingPivotInstances, (pivotInstance) => {
        return _.includes(rows, pivotInstance[this.relatedForeignKey])
      })
    } else {
      this._existingPivotInstances = []
    }
    return query.delete()
  }
```

Tương ứng khi detach sai method sync của bạn cũng bị sai theo
Sửa hàm detach này có thể sửa luôn được sync nhưng mình thấy việc xóa đi add lại hết của method sync không ổn lắm nên sửa method sync như thế này:

```

  async sync (references, pivotCallback) {
    const query = this.pivotQuery(false)
    query.where(this.foreignKey, this.$primaryKeyValue)
    if (references) {
      const rows = !Array.isArray(references) ? [references] : references
      query.whereNotIn(this.relatedForeignKey, rows)
      _.remove(this._existingPivotInstances, (pivotInstance) => {
        return _.includes(rows, pivotInstance[this.relatedForeignKey])
      })
    } else {
      this._existingPivotInstances = []
    }
    await query.delete()

    return this.attach(references, pivotCallback)
  }
```

Bạn xem như thế ổn không hay có góp ý gì khác

**Comment by duyluonglc** [comment]
Hi @haclongkim 
Can you tell me what's wrong of detach method? You said it has bug and the new code you changed but there is no reason :)

@Long có thể cho mình biết hàm detach hiện tại đang sai ở đâu và vì sao được không? mình thấy code sửa nhưng không ghi rõ lý do, nếu có thể tạo một case test

ps: nếu cần có thể chat với mình trên discord id này nhé #9447

**Comment by duyluonglc** [comment]
Xem lại code thì có nhiều vấn đề ở cả 2 hàm :)
fixed in v3.1.5
