### ISSUE TITLE
pass option { useNewUrlParser: true } to MongoClient.connect

### ISSUE THREAD

**Issue by alikkane** [duyluonglc/lucid-mongo#162]
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

**Comment by njhalaRhudara** [comment]
Yes You can pass the option to MongoClient 
Edit config/database.js

```
mongodb: {
    client: 'mongodb',
    connectionString: Env.get('DB_CONNECTION_STRING', ''),
    connection: {
      host: Env.get('DB_HOST', 'localhost'),
      port: Env.get('DB_PORT', 27017),
      username: Env.get('DB_USER', 'admin'),
      password: Env.get('DB_PASSWORD', ''),
      database: Env.get('DB_DATABASE', 'adonis'),
      options: {
         Your Option Here
         // replicaSet: Env.get('DB_REPLICA_SET', '')
        // ssl: ('DB_SSL, '')
        // connectTimeoutMS: Env.get('DB_CONNECT_TIMEOUT_MS', 15000),
        // socketTimeoutMS: Env.get('DB_SOCKET_TIMEOUT_MS', 180000),
        // w: ('DB_W, 0),
        // readPreference: Env.get('DB_READ_PREFERENCE', 'secondary'),
        // authSource: Env.get('DB_AUTH_SOURCE', ''),
        // authMechanism: Env.get('DB_AUTH_MECHANISM', ''),
        // other options
      }
    }
  }
```

Other Way Please [Read This](https://stackoverflow.com/questions/50448272/avoid-current-url-string-parser-is-deprecated-warning-by-setting-usenewurlpars)

**Comment by alikkane** [comment]
Thanks a lot















*ALIKKANE AYOUB*


*Développeur Full-Stack Chez Nickel ITIngénieur d'état - Génie Informatique*


*École Nationale des Sciences Appliquées *
*Université Cadi Ayyad | ENSA SafiMaroc*



Le jeu. 15 nov. 2018 à 20:02, njhalaRhudara <notifications@github.com> a
écrit :
