### ISSUE TITLE
invalid connection type

### ISSUE THREAD

**Issue by kuamatzin** [duyluonglc/lucid-mongo#169]
I'm getting invalid connection type when I add the 'lucid-mongo/providers/LucidMongoProvider' in the providers array in app.js

The error is in:

node_modules/lucid-mongo/src/Database/index.js

`
 * @group Database
 */
class Database {
  constructor (config) {
    if (config.client !== 'mongodb') {
      throw new CE.RuntimeException('invalid connection type')
    }

    if (config.connectionString) {
      this.connectionString = config.connectionString
      const parsedUri = mongoUrl(this.connectionString)
                
`

**Comment by duyluonglc** [comment]
can you check your config file?

**Comment by DeVoresyah** [comment]
Hi, I'm also getting this error
here's my `.env` configuration
```
DB_CONNECTION_STRING=mongodb://
DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_USER=admin
DB_PASSWORD=admin
DB_DATABASE=vuedo
```

**Comment by emacielxp** [comment]
@duyluonglc i'm having the same issue, when i use as default connection the postgresql (pg)

and add 'lucid-mongo/providers/LucidMongoProvider' as providers in app.js
and 'lucid-mongo/providers/MigrationsProvider' as aceProvioders in app.js

has any way to use lucid-mongo with another database at the same time?
