### ISSUE TITLE
Looking for value of specific array index

### ISSUE THREAD

**Issue by lukaszflorczak** [duyluonglc/lucid-mongo#170]
Hi. In my collection I have documents like that:

```
{
    year: 2019,
    schedule: [
        {finished: true, otherData: ...},
        {finished: true, otherData: ...},
        {otherData: ...},
        ...
    ]
}
```

Now I would like to get all documents, wher for example `schedule[1].finished` is `true`. So I need to check specific index of an array. Is it possible?

**Comment by duyluonglc** [comment]
Sorry @lukaszflorczak I think it impossible. As your data, I usually move schedule_items to other collection
