### ISSUE TITLE
Error with near query

### ISSUE THREAD

**Issue by devfelipereis** [duyluonglc/lucid-mongo#173]
Hello. 

I can't use near :/

"@adonisjs/framework": "^5.0.9"
"lucid-mongo": "^3.1.5"

The error: 'error processing query: ns=mean.sitiosTree: GEONEAR  field=location maxdist=1.79769e+308 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error: unable to find index for $geoNear query'

The index:

![image](https://user-images.githubusercontent.com/5348752/52448801-2fa60980-2b1c-11e9-9c08-a4e64782174f.png)

The model:

![image](https://user-images.githubusercontent.com/5348752/52448834-48aeba80-2b1c-11e9-8990-bc4c528d4b34.png)

The migration:

![image](https://user-images.githubusercontent.com/5348752/52449365-3897da80-2b1e-11e9-9daa-f41b2e946346.png)

Anything wrong?

**Comment by duyluonglc** [comment]
I'm not sure about the mongodb query near. Can you try with `dshpereIndexVersion: 2?
