### ISSUE TITLE
Mongodb 'referMany' support

### ISSUE THREAD

**Issue by mfatima96** [duyluonglc/lucid-mongo#178]
# Description

I am trying to populate my database references using `referMany` relation in mongoDb using `with` in the query. 

# What I am doing:

This is how I am declaring the relation between the models

```
class WorkOrder extends Model {
  WOType () {
    return this.referMany('App/Models/WoType', '_id', 'WOType')
  }
}
```
This is how I am saving the data in the model:

`await WorkOrder.save(); `

This is how I am querying the data.
```
const workOrders = await WorkOrder
      .with("WOType")
      .fetch();
```

# Expected Output:

I should get the populated field for the WOType.

# What is actually happening:

Instead of getting the populated field, i am getting null array.

```
"output": {
        "data": [
            {
                "_id": "5c8b625ce5b74448042ed953",
                "name": "Install asset",
                "siteId": "XYZ",
                "WOType": [],
                "WOProcess": "TagAsset",
                "transportRequired": "false",
                "processDetails": "Asset should be installed at XYZ",
                "created_at": "2019-03-15T08:29:16.483Z",
                "updated_at": "2019-03-15T08:29:16.483Z"
            }
        ]
    }
```

Now, my question is how can I configure it for populating the data? Is there something not configured correctly or what?

**Comment by duyluonglc** [comment]
Hi @mfatima96  can you try to use `W0TypeID` instead `W0Type` to store array of related data
```js
class WorkOrder extends Model {
  WOType () {
    return this.referMany('App/Models/WoType', '_id', 'WOTypeID')
  }
}
```
ps: try run project with DEBUG=mquery to see the the mongo query log
`DEBUG=mquery adonis serve --dev`

**Comment by mfatima96** [comment]
@duyluonglc It isn't making any difference.

As much as I have debugged the issue,  I got to know that as i am using EagerLoading, It is calling lucid-mongo's eagerLoad function.

```
  /**
   * Returns the eagerLoad query for the relationship
   *
   * @method eagerLoad
   * @async
   *
   * @param  {Array}          rows
   *
   * @return {Object}
   */
  async eagerLoad (rows) {
    const mappedRows = this.mapValues(rows)
    if (!mappedRows || !mappedRows.length) {
      return this.group([])
    }
    const relatedInstances = await this.relatedQuery.whereIn(this.primaryKey, mappedRows).fetch()
    let result = []
    rows.map(modelInstance => {
      relatedInstances.rows.map(related => {
        const foreignKeys = modelInstance[this.foreignKey] || []
        if (foreignKeys.map(String).includes(String(related.primaryKeyValue))) {
          const newRelated = new this.RelatedModel()
          newRelated.newUp(related.$attributes)
          newRelated.$sideLoaded[`refer_${this.foreignKey}`] = modelInstance.primaryKeyValue
          result.push(newRelated)
        }
      })
    })
    return this.group(result)
  }
```
which uses whereIn, but the `this.relatedQuery` does not have such associated function. 

I am not sure, but may be this is the reason of empty reference array?

**Comment by duyluonglc** [comment]
`DEBUG=mquery adonis serve --dev`
Did you try run with above command? How about console output?
How did you insert related ids?

**Comment by mfatima96** [comment]
Yep, I did. and this is the query it generated. 

` mquery find work_orders {} { fields: undefined }`

Also for saving the document i am simple using the following code.

```
await WorkOrder.save();
```
I am not sure about inserting related ids?

**Comment by duyluonglc** [comment]
Can look around the test script to know how to use referMany?
`https://github.com/duyluonglc/lucid-mongo/blob/develop/test/unit/lucid-refer-many.spec.js`
