### ISSUE TITLE
Example code of insert queries to seed data for models that have embedsMany and hasMany relation

### ISSUE THREAD

**Issue by isocroft** [duyluonglc/lucid-mongo#184]
Can i have an example of creating a seed file to insert data into a collection that contains a relation field to another collections' ObjectId field. Also, an example for a table that has an embedsMany relation.

It's quite confusing

**Comment by isocroft** [comment]
Hello @duyluonglc , I really need your help on this one please

**Comment by duyluonglc** [comment]
Sorry @isocroft I was too busy with projects and missed your issue. Please try to learn by read the test script instead

**Comment by duyluonglc** [comment]
most test scripts here:
https://github.com/duyluonglc/lucid-mongo/tree/develop/test/unit

and this is example how to create relate object
https://github.com/duyluonglc/lucid-mongo/blob/f073401b29cb1c4b569ed5b1e304fcd382fdda4b/test/unit/lucid-has-many.spec.js#L504

read more about other test case to understand how the relations works

**Comment by isocroft** [comment]
Thank you sooo very much. I appreciate so much

**Comment by golinmarq** [comment]
Hi! Can I use attach method to add a relationship? I'm trying to do it but it gives me an error saying the relationship is not a funcion
