### ISSUE TITLE
Adonis 4 session login error

### ISSUE THREAD

**Issue by suzet** [duyluonglc/lucid-mongo#201]
![Screen Shot 2019-07-10 at 3 37 09 PM](https://user-images.githubusercontent.com/11088836/60959949-d0e1f780-a328-11e9-8d86-23be3bbb89d4.png)

**Comment by duyluonglc** [comment]
@suzet did you set serializer to lucidMongo in /config/auth.js?

**Comment by suzet** [comment]
My bad created double hash password. Didn't see password hash by user hook
