### ISSUE TITLE
Rename _id to id

### ISSUE THREAD

**Issue by stas-sl** [duyluonglc/lucid-mongo#21]
Hi, is it possible to rename _id to id?

I've tried, but without any effect:
```
class MyModel extends Model {
  ...
  static get primaryKey () {
    return 'id'
  }
  ...
}
```

**Comment by duyluonglc** [comment]
@stas-sl sorry I did not test this case. I think current should keep primary key as _id

**Comment by wxs77577** [comment]
if you just wanna add a `id` field, you can try to use computed attribues:
```javascript
static get computed () {
    return ['id']
  }

  getId () {
    return this._id
  }
```
