### ISSUE TITLE
Cannot find module 'mongodb-core'

### ISSUE THREAD

**Issue by Nainabbas** [duyluonglc/lucid-mongo#223]
I am trying to use this package with adonisJs with everything set up as mentioned in docs. but this error occurs when I tried to use any model in my controller. `Cannot find module 'mongodb-core'`

**Comment by omaratpxt** [comment]
looks like dependency is missing

`npm i mongodb-core` to install the missing module

**Comment by Nainabbas** [comment]
`adonis install mongodb-core` worked for me
