### ISSUE TITLE
Override model table

### ISSUE THREAD

**Issue by gsbarreto** [duyluonglc/lucid-mongo#240]
Hi guys!
I'm refactoring an api that use Parse Server with mongodb, and looking in the [Documentation](https://adonisjs.com/docs/4.1/lucid#_convention_over_configuration), i saw that i can change the table name but changing the name of the Model there is no change on the functionality. There are any method to do this?

Thanks!

**Comment by rizalgunawan** [comment]
Try this https://github.com/duyluonglc/lucid-mongo/issues/143#issuecomment-424290219

**Comment by gsbarreto** [comment]
Thanks you! It solve my issue!
