### ISSUE TITLE
Roadmap for next version?

### ISSUE THREAD

**Issue by wxs77577** [duyluonglc/lucid-mongo#27]
Hi, do you have any roadmap for the next version? I think this project is the best mongodb ODM library and I hope to I could use it in other frameworks such as Express.js

Thank you!

**Comment by duyluonglc** [comment]
@wxs77577 I'm woking for new version. New version using async await of nodejs 7 and it can run standalone without adonisjs

**Comment by wxs77577** [comment]
@duyluonglc thanks a lot. when will you release it? 👍

**Comment by duyluonglc** [comment]
May be next weekend. But not sure :)

**Comment by duyluonglc** [comment]
released
