### ISSUE TITLE
error when use `sum` with relations

### ISSUE THREAD

**Issue by wxs77577** [duyluonglc/lucid-mongo#29]
It seems I can't use `sum()` for relation?

code: 
`yield customer.transactions().sum('amount')`

and I get the result of all records, without any `where` condition.

query log:
`mquery sum transactions {} { _id: '$undefined', sum: { '$sum': '$amount' } } +3ms`

**Comment by duyluonglc** [comment]
@wxs77577 thanks for reported
fixed at branch 1.x
