### ISSUE TITLE
Cannot store ObjectID data type to session store

### ISSUE THREAD

**Issue by kamatcho** [duyluonglc/lucid-mongo#36]
when i'm trying to logged in i find this error 

here is my model 
'use strict'

const Model = use('Model')

class User extends Model {
  static boot () {
    super.boot()

    /**
     * A hook to bash the user password before saving
     * it to the database.
     *
     * Look at `app/Models/Hooks/User.js` file to
     * check the hashPassword method
     */
    this.addHook('beforeCreate', 'User.hashPassword')
  }

  /**
   * A relationship on tokens is required for auth to
   * work. Since features like `refreshTokens` or
   * `rememberToken` will be saved inside the
   * tokens table.
   *
   * @method tokens
   *
   * @return {Object}
   */
  tokens () {
    return this.hasMany('App/Models/Token')
  }
}

module.exports = User

and my controller function 

  async login ({ request,session, auth }) {
   const test = await auth.attempt(request.input('email'),request.input('password'));
   console.log(test)

   // return 'Logged in successfully'
  }

also config/auth.js
'use strict'

module.exports = {
  /*
  |--------------------------------------------------------------------------
  | Authenticator
  |--------------------------------------------------------------------------
  |
  | Authentication is a combination of serializer and scheme with extra
  | config to define on how to authenticate a user.
  |
  | Available Schemes - basic, session, jwt, api
  | Available Serializers - lucid, database
  |
  */
  authenticator: 'session',

  /*
  |--------------------------------------------------------------------------
  | Session
  |--------------------------------------------------------------------------
  |
  | Session authenticator makes use of sessions to authenticate a user.
  | Session authentication is always persistent.
  |
  */
  session: {
    serializer: 'lucid',
    model: 'App/Models/User',
    scheme: 'session',
    uid: 'email',
    password: 'password'
  }

result of consol
![screenshot at sep 18 13-26-16](https://user-images.githubusercontent.com/11474418/30540094-e98c6bdc-9c75-11e7-9deb-bfc7dc06699d.png)

adonis support told me it's package error .... and the error is in serialize

**Comment by duyluonglc** [comment]
This issue cause the session only supports basic JavaScript data types (String, Number, boolean, etc), not custom object types such as ObjectId. With adonis v3 have no issue
you can try convert to json before store to session by this way
```js
Route.post('/login', async ({request, auth}) => {
  const { email, password } = request.all()

  // await auth.attempt(email, password) // replace this

  const user = await auth.validate(email, password, true)

  await auth.login(user.toJSON())

  // login success
  ...
}
```

**Comment by kamatcho** [comment]
Thanks For Ur Time ... Great Work
