### ISSUE TITLE
Ability to connect to replica set and specify other mongo options.

### ISSUE THREAD

**Issue by omanizer** [duyluonglc/lucid-mongo#40]
Best way I've seen to provide this config would be something like this:

```
{
  connection: 'mongodb',
  mongodb: {
    client: 'mongodb',
    connection: {
      host: 'localhost',
      options: {
        connectTimeoutMS: 15000,
        socketTimeoutMS: 180000,
        replicaSet: 'myReplicaSet'
      }
    }
  }
}
```

This way it would be possible to pass through other options (like the above timeouts) specific to the mongo client.  Looks like the connection string is the only thing that needs to be tweaked to support this.  I'm happy to make a PR if this config is acceptable.

**Comment by duyluonglc** [comment]
@omanizer welcome your PR
you can follow this issue to change the setting of v2
https://github.com/duyluonglc/lucid-mongo/pull/37/files

**Comment by duyluonglc** [comment]
sorry for late response, check new version 2.1.1
