### ISSUE TITLE
`objectIds()` for array data

### ISSUE THREAD

**Issue by wxs77577** [duyluonglc/lucid-mongo#42]
```javascript
module.exports = class AdminUser extends Model {
  
  static get objectIds(){
    return ['_id', 'role_ids']
  }
}
```
I store an array of roles objectIds in `role_ids`, but it stores as plain string instead `ObjectID` type to mongodb.

**Comment by duyluonglc** [comment]
https://github.com/duyluonglc/lucid-mongo/blob/develop/src/LucidMongo/Model/Base.js#L344
Current only support convert from String to ObjectID
@wxs77577 can you make a PR?

**Comment by duyluonglc** [comment]
no response from issue reporter
