### ISSUE TITLE
UnhandlesPromiseRejection and Error

### ISSUE THREAD

**Issue by darmie** [duyluonglc/lucid-mongo#44]
I am getting this error whenever i try to run this command `./ace migration:run`

```(node:15772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: double colon in host identifier```

**Comment by duyluonglc** [comment]
@darmie I guest issue from your setting
check your .env file is correct?
```
HOST=127.0.0.1
PORT=3333
NODE_ENV=development
CACHE_VIEWS=false
APP_KEY=

DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_USER=test
DB_PASSWORD=test
DB_DATABASE=adonis

APP_URL=http://${HOST}:${PORT}
```

**Comment by darmie** [comment]
this command worked instead `./ace migratrion:Run` , the first letter in run had to be in caps
