### ISSUE TITLE
Set table name not working

### ISSUE THREAD

**Issue by GencBlakqori** [duyluonglc/lucid-mongo#46]
I'm trying to manually set the table name with the method that Lucid has, but it doesn't seem to work here:
`  
        static get table () {
                return 'my_model_renamed'
         }
`

I'm using Adonis 3.2

**Comment by duyluonglc** [comment]
Try this `static get collection() { return 'user' }`

**Comment by GencBlakqori** [comment]
@duyluonglc  Nice man that works. Thank you very much for your fast response 👍
