### ISSUE TITLE
Belongs to many not working with one model connected to multiple models

### ISSUE THREAD

**Issue by GencBlakqori** [duyluonglc/lucid-mongo#47]
My problem is as follows:
I have these three tables:

> news
> class_codes
> class_code_new

So News have many ClassCodes and ClassCodes have many News, so a "belongsToMany" relationship ( I have added the belongsToMany configuration methods on each model. I only need it from the "New" model to get the class codes for each news).

I have lets say News 1 and 2 and I have only Class Code 1. Each of the News have this class code, so the pivot table looks something like this:

> _id, new_id, class_code_id
> 1, 1, 1
> 2, 2, 1

When I make a query like this:
`New.with('classCodes').fetch()` or `New.with('classCodes').paginate(1, 2)`
, as a result I get an array of news ( so New 1 and 2 ), but only New 1 has the class codes attached. The class codes in the second New is empty. This is what the results should be like:
```
[
    {
        "_id": "59f1d4d01f1f6243f3ae9b4c",
        "title": "New 1",
        "classCodes": [
            {
                "_id": "59f74f81bf938e8aca911915",
                "name": "Class Code 1"
            }
        ]
    },
    {
        "_id": "59f751aebf938e8aca911a17",
        "title": "New 2",
        "classCodes": [
            {
                "_id": "59f74f81bf938e8aca911915",
                "name": "Class Code 1"
            }
        ]
    }
]
```
and this is what I'm getting instead:
```
[
    {
        "_id": "59f1d4d01f1f6243f3ae9b4c",
        "title": "New 1",
        "classCodes": [
            {
                "_id": "59f74f81bf938e8aca911915",
                "name": "Class Code 1"
            }
        ]
    },
    {
        "_id": "59f751aebf938e8aca911a17",
        "title": "New 2",
        "classCodes": []
    }
]
```

Any idea why is this the case ?
BTW: I inserted them in the pivot table from the built in method create on the relationship, like this:
```
var news1 = New.first();
var news2 = New.last();
var classCode1 = ClassCode.first();
news1.classCodes().save(classCode1);
news2.classCodes().save(classCode1);
```

**Comment by duyluonglc** [comment]
I got this error from attach method. There are something wrong when check existing pivot data. will fix soon

**Comment by GencBlakqori** [comment]
@duyluonglc  I'm using version 1.0.51 btw for Adonis 3.2.

**Comment by GencBlakqori** [comment]
@duyluonglc  I'm using version 1.0.51 in Adonis 3.2.
I searched a bit in the code and maybe it has to do something with the line 283 in the BelongsToMany class:

```
    results = this._addPivotKeys(results, pivots)

    return results.groupBy((result) => {
      return _.find(pivots, pivot => {   // <--------- This line
        return String(pivot[this.pivotOtherKey]) === String(result._id)
      })[this.pivotLocalKey]
    }).mapValues(function (value) {
      return helpers.toCollection(value)
    }).value()
```
 As I could see, you have there the pivots and the results that you get from the other table and you want to map then the results to the pivots. But the thing with the "**_find**" method is that it's only finding the first pivot who's "**_pivotOtherKey_**" is equal to "**_result._id_**". That means that in this case, for the news for example, if we have "**_News1_**" and "**_News2_**" and both have "**_ClassCode1_**",  the "**__find_**" method is only returning "**_News1_**". Therefore as a result when I fetch them, only "**_News1_**" gets this class code and the other one doesn't.

**Comment by duyluonglc** [comment]
@GencBlakqori fixed
can you check the new version

**Comment by GencBlakqori** [comment]
@duyluonglc  Yes! Works good now. I'll keep you updated if I run again into an issue. Thanks for the support!
