### ISSUE TITLE
Relationships on children?

### ISSUE THREAD

**Issue by wxs77577** [duyluonglc/lucid-mongo#49]
Hi, thanks for your help first.

I have a `Order` model like this: 
> Just only one orders collection, not two collections.
```
{
  "no": "A12333333",
  "total": 46,
  "items": [
    {buyable_type: 'App/Models/Course', buyable_id: 'A7786887899E898F8', price: 19},
    {buyable_type: 'App/Models/Course', buyable_id: 'A7786887899E898F9', price: 27},
  ]
}
```

How can I add a morph relation on `items`  like this: 

```
buyable(){
  return this.morphTo('App/Model', 'items.buyable_type', 'items.buyable_id')
}
```
so I can access `buyable` objects of children?

**Comment by duyluonglc** [comment]
@wxs77577 
look this
https://github.com/duyluonglc/lucid-mongo/blob/develop/test/unit/lucid-morph-to.spec.js#L58

**Comment by wxs77577** [comment]
@duyluonglc Yeah, I know how to use morph relation via a Model, but I don't know how to use it via children objects. Now I think I should use `embedsMany` for `Order` and `OrderItem` , then use `mophTo` for `OrderItem`.

**Comment by mcordoba** [comment]
It would be nice when you explain the solution instead of close the issue without any explanation.
