### ISSUE TITLE
Can't query "referMany" relationships

### ISSUE THREAD

**Issue by GencBlakqori** [duyluonglc/lucid-mongo#50]
I have two models, one for my **_"news"_** and one for my **_"suppliers"_**.  At the news I specified the relation like this:
```
suppliers(){
   return this.referMany('App/Model/Supplier', "_id", "suppliers")
}
```

When I attach some supplier to a specific news it works well, so it saves it under the field **_"suppliers"_**, but when I try to query it, it keeps giving me this message:

> "message": "Cannot read property 'suppliers' of undefined",

This is how I'm querying it:
```
yield New.with('suppliers').first()
```

and this is how I'm saving it:
```
yield New.suppliers().attach(yield Supplier.first())
```

BTW: I had quite a similar issue with the "embeds" relationships.

**Comment by duyluonglc** [comment]
yes I face this issue with old project, dont know what change affect to this.
version 1 I can not wrote unit test so it has many issues when update code
 I'll fix it asas but I suggest use lucid mongo v2 with adonis v4

**Comment by GencBlakqori** [comment]
@duyluonglc  Any update about this issue ?

**Comment by duyluonglc** [comment]
Sorry I'm busy with 2-3 projects at the moment. Will fix soon when I have more time

**Comment by duyluonglc** [comment]
@GencBlakqori 
check new version
