### ISSUE TITLE
`dates()` should avoid convert `null` value to `invild date` when fetching data

### ISSUE THREAD

**Issue by wxs77577** [duyluonglc/lucid-mongo#58]
I add `used_at` to `dates()` so that it can be displayed as date time,  but when I querying data use ` await Voucher.where({used_at: null})` to find vouchers not be used, the logs of mquery  is 

```
mquery findOne vouchers { used_at: Invalid Date } { fields: undefined } +5ms
null
```

**Comment by duyluonglc** [comment]
@wxs77577 can you try this?
```js
Voucher.where({used_at: { exists: false }})
// or
Voucher.where('used_at').exists(false)
```
