### ISSUE TITLE
Error: Where has is not a function

### ISSUE THREAD

**Issue by phanvannhien** [duyluonglc/lucid-mongo#60]
When i refresh token JWT

TypeError: this._getQuery(...).whereHas is not a function\n    at LucidSerializer.findByToken (/Library/WebServer/Documents/node_project/putty_adonis/node_modules/@adonisjs/auth/src/Serializers/Lucid.js:162:8)\n    at JwtScheme.generateForRefreshToken (/Library/WebServer/Documents/node_project/putty_adonis/node_modules/@adonisjs/auth/src/Schemes/Jwt.js:304:49)

**Comment by duyluonglc** [comment]
Thank for report I'll make a Serializer to full suport adonis/auth. May this weekend

**Comment by duyluonglc** [comment]
@phanvannhien 
I created the serializer. You can see the doc here
https://github.com/duyluonglc/lucid-mongo#configuring-auth-serializer

**Comment by phanvannhien** [comment]
@duyluonglc Thanks so much
