### ISSUE TITLE
Hook afterPaginate 

### ISSUE THREAD

**Issue by phanvannhien** [duyluonglc/lucid-mongo#63]
Can you development the Hook afterPaginate like Lucid
Lucid Mongo: this._events = ['create', 'update', 'delete', 'restore', 'find', 'fetch']
Lucid: this._events = ['create', 'update', 'delete', 'restore', 'find', 'fetch', 'paginate']

So when i created afterPaginate Hook i got error: "message": "E_INVALID_PARAMETER: paginate is not a valid hook event",

**Comment by duyluonglc** [comment]
@phanvannhien 
I publish new version fixed this bug 
please check

**Comment by phanvannhien** [comment]
I tested with paginate Hook, it's working . Thanks so much @duyluonglc
