### ISSUE TITLE
Can't save date fields

### ISSUE THREAD

**Issue by GencBlakqori** [duyluonglc/lucid-mongo#64]
I'm using this attribute for the model to create dateFields:
```
static get dateFields () {
      return ['date']
}
```

However, it's not saving it correctly in the database. 

For example: I'm giving this date:
"_**2018-01-11T09:52:56.839Z**_"

And this gets stored in to the database:
"_**1970-01-01T00:00:00.000Z**_"

I am using Lucid mongo 1.1.0.

**Comment by GencBlakqori** [comment]
@duyluonglc  Any updates about this ?

**Comment by duyluonglc** [comment]
Hi @GencBlakqori 
for version 1 you need save the moment object to model, example
```js
  const car = yield Car.create({
    model: 'late-2016',
    warrantyDate: moment('2018-01-01')
  })
```
why do you not use adonis v4?

**Comment by GencBlakqori** [comment]
@duyluonglc  The thing is that I'm already in the project and would be a bit tight to change it from to 4.0 from 3.2. At least I don't have the time to do it right now :/ .

**Comment by GencBlakqori** [comment]
@duyluonglc  Btw it's still not working when I update the date. I tried to use this hard coded `moment('2018-01-01')` but it's not working for me.
