### ISSUE TITLE
I cannot update an object inside a embedsMany list

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/lucid-mongo#66]
Hello,

I'm trying to update an object inside a embedsMany list, but the result does not persist to the database.

Controller: 
```js
async update({
    request,
    response,
    instance,
    params
  }) {
    const embedInstance = await instance.emailContents()
      .find(params.emailId);
    embedInstance.merge(request.all())
    var result = await instance.emailContents().save(embedInstance)
    return response.apiUpdated(result)
  }
```

Models:

```js
const Model = use('Model')

class EmailContent extends Model {

    static get createTimestamp () { return 'createdAt' }
    static get updateTimestamp () { return 'updatedAt' }

}

class Campaign extends Model {

  user() {
    return this.belongsTo('App/Models/User')
  }

  emailContents() {
    return this.embedsMany('App/Models/EmailContent', '_id', 'emailContents')
  }

  banners() {
    return this.embedsMany('App/Models/BannerContent', '_id', 'banners')
  }

  textMessages() {
    return this.embedsMany('App/Models/TextMessageContent', '_id', 'textMessages')
  }
}
```

I have already created the object i want to create but i cannot update it.

**Comment by franciscosucre** [comment]
I think i found the problem, in the save function:

async save (relatedInstance) {
    if (relatedInstance instanceof this.RelatedModel === false) {
      throw CE.ModelRelationException.relationMisMatch('save accepts an instance of related model')
    }

    await this._persistParentIfRequired()

    let embeds = this.parentInstance.$attributes[this.foreignKey] ? _.cloneDeep(this.parentInstance.$attributes[this.foreignKey]) : []
    if (!Array.isArray(embeds)) {
      embeds = [embeds]
    }
    if (!relatedInstance.primaryKeyValue) {
      relatedInstance.primaryKeyValue = new ObjectID()
      embeds.push(relatedInstance.$attributes)
    } else {
      embeds = embeds.map(embed => {
        console.log("embed: ", embed)
        console.log("relatedInstance.$attributes: ", relatedInstance.$attributes)
        console.log("embed.primaryKeyValue: ", embed.primaryKeyValue)
        console.log("relatedInstance.primaryKeyValue: ", relatedInstance.primaryKeyValue)
        console.log("String(embed.primaryKeyValue) === String(relatedInstance.primaryKeyValue): ", String(embed.primaryKeyValue) === String(relatedInstance.primaryKeyValue))
        return String(embed.primaryKeyValue) === String(relatedInstance.primaryKeyValue) ? relatedInstance.$attributes : embed
      })
    }
    this.parentInstance[this.foreignKey] = embeds
    await this.parentInstance.save()
    return relatedInstance
  }

all this console logs give me this: 

embed:  { name: 'actualizado', _id: 5a5fd9a01653416da6efade9 }
relatedInstance.$attributes:  { name: 'actualizado',
  _id: 5a5fd9a01653416da6efade9,
  nombre: 'nueva cosa',
  atributo: 'actualizado' }
embed.primaryKeyValue:  undefined
relatedInstance.primaryKeyValue:  5a5fd9a01653416da6efade9
String(embed.primaryKeyValue) === String(relatedInstance.primaryKeyValue):  false
embed:  { name: 'actualizado', _id: 5a5fdac9c7ebe86e7ceb4775 }
relatedInstance.$attributes:  { name: 'actualizado',
  _id: 5a5fd9a01653416da6efade9,
  nombre: 'nueva cosa',
  atributo: 'actualizado' }
embed.primaryKeyValue:  undefined
relatedInstance.primaryKeyValue:  5a5fd9a01653416da6efade9
String(embed.primaryKeyValue) === String(relatedInstance.primaryKeyValue):  false

Looks like the embed is always giving undefined so it nevers updates the data

**Comment by franciscosucre** [comment]
Right now i have a working controller like this, note the replaced embed.primaryKeyValue by embed._id, but this loses some flexibility. I think we could find a way to obtains the embed as models, and not as pure objects, so we could use the existing comparison.

async update({
    request,
    response,
    instance,
    params
  }) {
    const embedInstance = await instance.EmailContent()
      .find(params.emailId);
    if (!embedInstance) {
      throw ResourceNotFoundException.invoke(`Can not find model with id "${params.emailId}"`)
    }

    let embeds = instance.$attributes.emailContents ? _.cloneDeep(instance.$attributes.emailContents) : []
    embedInstance.merge(request.all())

    embeds = embeds.map(embed => {
      return String(embed._id) === String(embedInstance.primaryKeyValue) ? embedInstance.$attributes : embed
    })
    instance.$attributes.emailContents = embeds
    await instance.save()
    return response.apiUpdated(embedInstance)
  }

Sorry for all the post. All i want is to contribute to this project.

**Comment by franciscosucre** [comment]
Here is a working solution for the problem, i would like it to be included in the lucid embedsMany Model if you think it works.

**Comment by duyluonglc** [comment]
Hi @franciscosucre 
Thank for your report
1. I can not read your code, please put your code to markdown code block like this
\`\`\`js
  // put your code here
\`\`\`
2. I made a test script saving existing relation here:
https://github.com/duyluonglc/lucid-mongo/blob/develop/test/unit/lucid-embeds-many.spec.js#L257

**Comment by franciscosucre** [comment]
Hi @duyluonglc , thanks for your feedback.

1. I edited all the code in my comments, i did not know how to format code here as this is the first time i really report an issue.
2. The script you use is just a wrote in the first comment, "await user.emails().save(email)", beign emails an embedsMany relationship, it is just as i wrote it in my code. The save function told me it was successful but it did not change the contents of the database. When i went to see the source code and exam it with consoles logs i saw something that i mentioned on a previews comment. In the map callback, the embed is not a modelInstance but a plain object, so when you call "embed.primaryKeyValue", the result is always undefined, so the equal comparison after it will never be true. I made a fix for this that is working for me in a fork of your code which already has a pull request, so you could see it and decide if it makes sense. 

Maybe i am using the function wrong, but if that is the case i would like you correct me, thank you!

With my fix, this controllers updates the objects in the database:

```js
async update({
    request,
    response,
    instance,
    params
  }) {
    const embedInstance = await instance.emailContents()
      .find(params.emailId);
    embedInstance.merge(request.all())
    var result = await instance.emailContents().save(embedInstance)
    return response.apiUpdated(result)
  }
```

As you can see, i find an object from the list, i modify it and send it to the save function.

**Comment by franciscosucre** [comment]
Well executing the script it works, but with my models it does not work :(

**Comment by duyluonglc** [comment]
@franciscosucre 
check new version
https://github.com/duyluonglc/lucid-mongo/blob/develop/CHANGELOG.md#224-2018-01-21

**Comment by franciscosucre** [comment]
Hi @duyluonglc , thanks for including my fix! I happy to contribute to this project. If I can continue to do it I will. One thing I do want to ask for is a little more documentation on querying relationships, I mean more examples la querying a embeds Many relation o a has Many, but not querying the parent model like in the existing examples.
