### ISSUE TITLE
fields in the objectIds getter are not getting stored as ObjectIDs

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/lucid-mongo#69]
I am using the create command through a relationship but the reference is always stored as a string and not as an objectId. Then when i try to query those objects i cannot find them, excepto if a manually enter the database and edit them. I can simple create directly from the Related Model but i find really intuitive to create them through the relationship

**My Model:**

```js
const Model = use('Model')

class Group extends Model {
  contacts() {
    return this.hasMany('App/Models/Contact')
  }

  user() {
    return this.belongsTo('App/Models/User')
  }

  static get objectIds() {
    return [
      this.primaryKey,
      'user_id'
    ]
  }

}
```

My Controller:

```js
  async uploadContactsByFile({
    request,
    response,
    auth
  }) {
    const user = await auth.getUser();
    const group = await user.groups().create({
      "name":file.clientName,
    })
    return response.apiCreated(group)
```

**Comment by franciscosucre** [comment]
I think the problem could be here, where the primary key value is obtained:
```js
/**
   * Returns the value for the primary key set on
   * the relationship
   *
   * @attribute $primaryKeyValue
   *
   * @return {Mixed}
   */
  get $primaryKeyValue () {
    return this.parentInstance[this.primaryKey]
  }
```
And then here where it is stored:
```js
async create (payload) {
    await this._persistParentIfRequired()
    payload[this.foreignKey] = this.$primaryKeyValue
    return this.RelatedModel.create(payload)
  }
```

We are obtain a string form of the primaryKey and then we are storing it directly as a string in the foreignKey. I think we should verify here if it is an objectId and store it as such.

**Comment by duyluonglc** [comment]
@franciscosucre there is a typo in document 😆 
use objectIDs instead objectIds
you can see some test case here
https://github.com/duyluonglc/lucid-mongo/blame/10e10847256873c62fcfdb5cd7c139807f26efc7/test/unit/field-format.spec.js#L536

**Comment by franciscosucre** [comment]
Just found the typo jajaja sorry for the problems.
