### ISSUE TITLE
Select fields in get all users

### ISSUE THREAD

**Issue by bryannbarbosa** [duyluonglc/lucid-mongo#76]
I am using the following code to acquire all registered users
**const user = await User.all()**

The return of this code is this:

{
            "_id": "5a75ef1ddcd123280c12e49c",
            "name": "Bryann Barbosa",
            "email": "bryannbarbosa@gmail.com",
            **"password": "$2a$10$5rYbEs9XdoRHaPeIer7rH.4/1zHTfu0G/1xA9IkqKz4eJZpBVxkvm",**
            "user_type": "administrator",
            "address": "São José dos Campos",
            "created_at": "2018-02-03 15:19:25",
            "updated_at": "2018-02-03 15:19:25"
        }

however, I want to hide the password field, or even more fields, if necessary, how can I do this using this library?

**Comment by duyluonglc** [comment]
try select(...) to limit fields on query builder
```js
const users = await User.select(['_id', 'email']).fetch()
```
other way you can hide fields by put to hidden attribute
```js
class User extends Model {
  static get hidden () {
    return ['password']
  }
}
```
see Lucid officer document here, there are many features of LucidMongo like Lucid
http://adonisjs.com/docs/4.0/lucid#_hiding_fields
