### ISSUE TITLE
Documents in embedMany relationship do not activate hooks

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/lucid-mongo#77]
I have an embedMany relationship and when i save an instance no hook is called. I would like to know if this is possible and if not, how could i simulate it.

**Comment by duyluonglc** [comment]
fixed at 3.0.1

**Comment by franciscosucre** [comment]
I am going to test @duyluonglc , thank you! The hooks are activated on the embedInstance or the fatherInstance?
