### ISSUE TITLE
Cannot query embedded objects

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/lucid-mongo#79]
I cannot query an embedsMany relationship, i already examined the code and it looks like the only options are:

1. Obtain all (fetch method)
2. Obtain the first one (first method)
3. Obtain one by id (find method)

I need to query my embedsMany relationship in other ways, even by a naive implementation of a query method and this would give lucid-mongo more value.

**Comment by duyluonglc** [comment]
Yes there are only 3 options because these field is an array. how about to use lodash.filter to query that field?

**Comment by franciscosucre** [comment]
I have been using lodash for it. But i have to questions ¿ If the array is to big would that create a performance issue? ¿Would it be possible to implement a query using lodash on a lower level to mantain standards? 

Thanks!
