### ISSUE TITLE
How to make text search queries?

### ISSUE THREAD

**Issue by franciscosucre** [duyluonglc/lucid-mongo#81]
Hi, i would like to see an example of a text search query with lucid-mongo. If it is possible i would like an example of a migration creating a text index too. Probably is something simple but a cannot find an example in the documentation

**Comment by duyluonglc** [comment]
sorry for late response
current it does not support text search
after some projects I see current querybuilder has limit query so I think should rewrite querybuilder

**Comment by franciscosucre** [comment]
wow thanks @duyluonglc! you are awesome!

**Comment by duyluonglc** [comment]
ah yes your are right it should be `{ $name: { $search : "value" } }`

**Comment by duyluonglc** [comment]
@franciscosucre did you success with search?

**Comment by franciscosucre** [comment]
Hey @duyluonglc , i got an update on this.

The following query works:

```js
const genders = (await Gender.where({
      $text: {
        $search: "male",
      }
    }).fetch()).rows
```

But the following does not:

```js
const genders = (await Gender.where({
      $text: {
        $search: "fe",
      }
    }).fetch()).rows
```

This is the index:

```js
{
        keys: {
          name: "text"
        },
        options: {
          name: "text_index",
          unique: true
        }
      }
```

In gender the following documents exist:

```js
/* 1 */
{
    "_id" : ObjectId("5abc805f8c51b71b4c6dd8af"),
    "name" : "Male",
    "created_at" : ISODate("2018-03-29T05:57:51.126Z"),
    "updated_at" : ISODate("2018-03-29T05:57:51.126Z")
}

/* 2 */
{
    "_id" : ObjectId("5abc805f8c51b71b4c6dd8b0"),
    "name" : "Female",
    "created_at" : ISODate("2018-03-29T05:57:51.130Z"),
    "updated_at" : ISODate("2018-03-29T05:57:51.130Z")
}
```

**Comment by franciscosucre** [comment]
I think this is a normal behavior in mongodb (i think mongodb does not make partial search?), but i am not sure. Correct me if i am wrong please!

**Comment by franciscosucre** [comment]
Indeed, mongodb does not support partial search, so your implementation for the $text search is perfect! Thanks again @duyluonglc you are awesome!
