### ISSUE TITLE
Can't get authentication working (E_INVALID_SESSION: Invalid session)

### ISSUE THREAD

**Issue by johnRivs** [duyluonglc/lucid-mongo#84]
I've read #36 and I'm doing something like this:
```js
let channel = await Channel.findBy('name', 'something');
await auth.login(channel.toJSON());
```
No error is thrown. Then, when I visit a route with the `auth` middleware applied to it, I get this `401` error:
![](https://i.imgur.com/UxCWWHs.png)
Here's `config/auth.js`:
```js
session: {
    serializer: 'LucidMongo',
    model: 'App/Models/Channel',
    scheme: 'session',
    uid: '_id',
    password: 'password'
}
```
And here's the model:
```js
let Model = use('Model');

class Channel extends Model {
    static get primaryKey() {
        return '_id';
    }
}

module.exports = Channel;
```

**Comment by duyluonglc** [comment]
Hi @johnRivs 
check this repo: `https://github.com/duyluonglc/adonis-mongdb-session-login-test`
first open url `http://localhost/login`
then open url `http://localhost/check`
