### ISSUE TITLE
Error with near query

### ISSUE THREAD

**Issue by tavsta** [duyluonglc/lucid-mongo#87]
Have issue when using `near` query.

        const query = Stock.where({
            location: {
                near: { latitude: 1, longitude: 2 }
            }
        });

Error message:
`error processing query: ns=adidi_stock.stocksTree: GEONEAR field=location maxdist=1.79769e+308 isNearSphere=0 Sort: {} Proj: {} planner returned error: unable to find index for $geoNear query`

For migration:

        this.collection('stocks', (collection) => {
            collection.index('location_index', { location: '2dsphere' }, { '2dsphereIndexVersion': 2 })
        })

**Comment by duyluonglc** [comment]
Hi @tavsta did you run `adonis migrate` ?
You can add index by hand then test

**Comment by tavsta** [comment]
How to return distance in this query?
