### ISSUE TITLE
Cannot remove embedded document in a nested array of documents

### ISSUE THREAD

**Issue by vpsudhin** [duyluonglc/lucid-mongo#98]
Hi Team,
My schema looks like this:

    {
    "_id" : ObjectId("5ad9e8e4e4050a464b083258"),
    "courseId" : ObjectId("5ad9e8cde4050a464b083256"),
    "title" : "Introduction",
    "status" : "Active",
    "resources" : [ 
        {
            "title" : "Study Materials",
            "details" : [ 
                {
                    "itemCode" : "MINT-1524219357914",
                    "title" : "Finance ",
                    "format" : "Video"
                }, 
                {
                    "itemCode" : "MINT-1524213969212",
                    "title" : "Account",
                    "format" : "Ebook"
                }, 
                {
                    "itemCode" : "MINT-1524219357914",
                    "title" : "Finance Video",
                    "format" : "Video"
                }, 
                {
                    "itemCode" : "MINT-1524213969212",
                    "title" : "Tax",
                    "format" : "Ebook"
                }
            ]
        }, 
        {
            "title" : "Videos",
            "details" : [ 
                {
                    "itemCode" : "MINT-1524408901486",
                    "title" : "Test video",
                    "format" : "Video"
                }
            ]
        }
    ],
    "createdAt" : ISODate("2018-04-20T13:19:32.317Z"),
    "updatedAt" : ISODate("2018-04-22T14:55:09.073Z")
     }

I want remove the document from resources->details , which is having itemCode  'MINT-1524219357914
Below is the query i have writtern

    await mongoClient.collection('course_modules')
                .update({_id :  ObjectId("5ad9e8e4e4050a464b083258") }, { $pull: { 'resources.$.details': { $elemMatch: { 'itemCode': 'MINT-1524219357914' } } } }, { multi: true })

When i run this query im getting an Error:

       { MongoError: The positional operator did not find the match needed from the query. Unexpanded update: resources.$.details
    at Function.MongoError.create (/opt/lampp/htdocs/nodeApps/l_and_ls/node_modules/mongodb-core/lib/error.js:45:10)
    at toError (/opt/lampp/htdocs/nodeApps/l_and_ls/node_modules/mongodb/lib/utils.js:149:22)
    at /opt/lampp/htdocs/nodeApps/l_and_ls/node_modules/mongodb/lib/collection.js:1035:39
    at /opt/lampp/htdocs/nodeApps/l_and_ls/node_modules/mongodb-core/lib/connection/pool.js:544:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
         name: 'MongoError',
        message: 'The positional operator did not find the match needed from the query. Unexpanded 
      update: resources.$.details',
       driver: true,
       index: 0,
      code: 16837,
       errmsg: 'The positional operator did not find the match needed from the query. Unexpanded update: 
       resources.$.details' }

  I i'm not seeing any issue with this query. Can anyone help me out to fix this issue...??

**Comment by duyluonglc** [comment]
Sorry @vpsudhin it's a long time
I write this library but I have not much experience with mongodb :)
